version: "3"
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - ${QDRANT_API_PORT}:6333
      - ${QDRANT_GRPC_PORT}:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./data/qdrant-data:/qdrant/storage

networks:
  rag-project:

volumes:
  qdrant-data:

configs:
  qdrant_config:
    content: |
      log_level: INFO 
