[run]
pipeline = true
indexing = false
analysis = false
evaluation = false
evaluation_multi = false

# choose from "sec-filings", "wiki-table-questions"
dataset = "sec-filings"
retriever_num_documents = 3

[indexing]

# choose from "recursive-character", "recursive-character-html", "semantic", "text-only-chunking"
chunking_strategy = "semantic"

# choose out of "huggingface", "nomic", "openai", "fast_embed", ...
embedding_method = "openai"

full_document_storage_path = "./data/preprocessed_documents/"


[text_generation]

# choose from "ollama", "huggingface","openai", ...

method = "openai"

prompt_template = '''
You are tasked with answering questions based on specific financial documents. Your task is to give the correct answer based on the given context.
Respond with only the answer. Do not include words like "Answer" or "Response." Provide the answer as either:
- A number for questions about revenue, profit, or quantities.
- A word or phrase for questions about products, categories, or names.
- 'None' if the context doesn't provide information about the given question.

Do not include explanations, units, or any additional text. Provide only the final answer.

Example:
- What was the sales revenue of Company Y from 2022 to 2024?
  2,500
- What is the main product of Company Z?
  ZetaDrug
- What's stock market price of Company X in 2021?
  None

Context: 
{context}

Question: {question}
'''

[ollama]

# choose out of "gemma:2b", "mistral-nemo"
model = "gemma:2b"

[huggingface]

# choose out of "mistralai/Mistral-Nemo-Instruct-2407", "google/gemma-2-2b-it"
generation_model = "mistralai/Mistral-Nemo-Instruct-2407"

# choose out of "sentence-transformers/all-MiniLM-l6-v2", "Snowflake/snowflake-arctic-embed-m-v1.5", "Alibaba-NLP/gte-base-en-v1.5"
embedding_model = "Snowflake/snowflake-arctic-embed-m-v1.5"

[nomic]
embedding_model = "nomic-embed-text-v1.5"

[openai]
embedding_model = "text-embedding-ada-002"

generation_model = "gpt-4o-mini"

max_tokens = 100

[fast_embed]
embedding_model = "BAAI/bge-small-en-v1.5"

[sec_filings]
data_path = "./data/sec_filings/"
data_path_single = "./data/sec_filings/awk-20231231.htm"
evaluation_data_path = "./data/evaluation/SEC_Evaluation_Dataset_AWW.csv"

[wiki_table_questions]
is_single_evaluation = true
single_document_id = "204-577"
data_path = "./data/wiki_table_questions/"

[evaluation]
evaluate_qa = true
evaluate_ir = true
run_document_analysis = false
num_of_documents = 10

# Options are 
#       - "none", 
#       - "basic" which contains ("remove-attributes", "remove-xbrl", "remove-invisible", "remove-spans-a")
#       - "only-text-except-tables".

preprocess_config = {name = "basic", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records"}

preprocess_configs_multi = [
  {name = "no-preprocessing", reduced_sections = false, preprocess_mode = ["none"], ignore_tables_for_embeddings = false, table_serialization = "none"},
  {name = "basic", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "none"}
#  {name = "none", reduced_sections = false, preprocess_mode = ["none"], tables_for_embeddings = false, table_serialization = "none"},
#   {name = "basic", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "none"},
#   {name = "only-text", reduced_sections = false, preprocess_mode = ["basic", "only-text-except-tables"], ignore_tables_for_embeddings = false, table_serialization = "none"},
#  {name = "none-reduced", reduced_sections = true, preprocess_mode = ["none"], ignore_tables_for_embeddings = false, table_serialization = "none"},
#  {name = "basic-reduced", reduced_sections = true, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "none"},
# {name = "only-text-reduced", reduced_sections = true, preprocess_mode = ["basic", "only-text-except-tables"], ignore_tables_for_embeddings = false, table_serialization = "none"},
#  {name = "embeddings-without-tables", reduced_sections = false, preprocess_mode = ["basic", "only-text-except-tables"], ignore_tables_for_embeddings = true, table_serialization = "none"},
#  {name = "embeddings-with-tables", reduced_sections = true, preprocess_mode = ["basic", "only-text-except-tables"], ignore_tables_for_embeddings = false, table_serialization = "none"}
]










