[run]
pipeline = true
indexing = false
analysis = false
evaluation = false
evaluation_multi = false

# choose from "sec-filings", "wiki-table-questions"
dataset = "sec-filings"
retriever_num_documents = [3]


[indexing]

# choose from "recursive-character", "recursive-character-html", "semantic", "text-only-chunking"
chunking_strategy = "semantic"

# choose out of "huggingface", "nomic", "openai", "fast_embed", ...
embedding_method = "openai"

full_document_storage_path = "./data/preprocessed_documents/"


[text_generation]

# choose from "ollama", "huggingface","openai", ...

method = "openai"

prompt_template = '''
You are tasked with answering questions based on specific financial documents. Your task is to give the correct answer based on the given context.
Respond with only the answer. Do not include words like "Answer" or "Response." Provide the answer as either:
- A number for questions about revenue, profit, or quantities.
- A word or phrase for questions about products, categories, or names.
- 'None' if the context doesn't provide information about the given question.

Do not include explanations, units, or any additional text. Provide only the final answer.

Example:
- What was the sales revenue of Company Y from 2022 to 2024?
  2,500
- What is the main product of Company Z?
  ZetaDrug
- What's stock market price of Company X in 2021?
  None

Context: 
{context}

Question: {question}
'''

[ollama]

# choose out of "gemma:2b", "mistral-nemo"
model = "gemma:2b"

[huggingface]

# choose out of "mistralai/Mistral-Nemo-Instruct-2407", "google/gemma-2-2b-it"
generation_model = "mistralai/Mistral-Nemo-Instruct-2407"

# choose out of "sentence-transformers/all-MiniLM-l6-v2", "Snowflake/snowflake-arctic-embed-m-v1.5", "Alibaba-NLP/gte-base-en-v1.5"
embedding_model = "Snowflake/snowflake-arctic-embed-m-v1.5"

[nomic]
embedding_model = "nomic-embed-text-v1.5"

[openai]
embedding_model = "text-embedding-ada-002"

generation_model = "gpt-4o-mini"

max_tokens = 100

[fast_embed]
embedding_model = "BAAI/bge-small-en-v1.5"

[sec_filings]
data_path = "./data/sec_filings/"
data_path_single = "./data/sec_filings/awk-20231231.htm" #option: "./data/sec_filings/abnb-20231231.htm"  
evaluation_data_path = "./data/evaluation/SEC_Evaluation_Dataset_AWW.csv"  # option: "./data/evaluation/SEC_Evaluation_Dataset_ABNB.csv"   
evaluation_get_header_data_path = "./data/evaluation/Header_Extraction_Evaluation.csv"

[wiki_table_questions]
is_single_evaluation = true
single_document_id = "204-577"
data_path = "./data/wiki_table_questions/"

[evaluation]
evaluate_qa = false
evaluate_ir = false
run_document_analysis = false
evaluate_get_headers = true
num_of_documents = 19

preprocess_config = {name = "basic-json-records", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false}
preprocess_configs_multi = [
      {name = "basic-json-records", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
      {name = "basic-json-records-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
      {name = "basic-json-split", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-split", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
      {name = "basic-json-split-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-split", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
      {name = "basic-json-index", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-index", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
      {name = "basic-json-index-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-index", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
      {name = "basic-matrix", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "matrix", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
      {name = "basic-matrix-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "matrix", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},

    # {name = "none", preprocess_mode = ["none"], ignore_tables_for_embeddings = false, table_serialization = "none", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
    # {name = "basic-none", preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "none", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false},
    # {name = "basic-html", preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "html", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false},
    # {name = "basic-html-text-only", preprocess_mode = ["basic"], ignore_tables_for_embeddings = true, table_serialization = "html", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false},
    # {name = "abnb-basic-html-merge-sentences", preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "html", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
    # {name = "basic-json-records", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
    # {name = "basic-json-records-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
    # {name = "basic-markdown", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "markdown", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
    #  {name = "basic-markdown-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "markdown", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
  # {name = "basic-csv", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "csv", consider_colspans_rowspans = false, merge_sentence_infront_of_table = false},
  # {name = "basic-csv-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "csv", consider_colspans_rowspans = false, merge_sentence_infront_of_table = true},
  # {name = "basic-json-records-colspans", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false},
  #   {name = "basic-json-records-merge-sentences-colspans", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "json-records", consider_colspans_rowspans = true, merge_sentence_infront_of_table = true},
  #  {name = "basic-markdown-colspans", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "markdown", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false},
  #   {name = "basic-markdown-colspans-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "markdown", consider_colspans_rowspans = true, merge_sentence_infront_of_table = true},
  # {name = "basic-csv-colspans", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "csv", consider_colspans_rowspans = true, merge_sentence_infront_of_table = false},
  # {name = "basic-csv-colspans-merge-sentences", reduced_sections = false, preprocess_mode = ["basic"], ignore_tables_for_embeddings = false, table_serialization = "csv", consider_colspans_rowspans = true, merge_sentence_infront_of_table = true},
]


[tabgraph]

llm_method = "openai"
llm_model = "gpt-4o-mini"
llm_max_tokens = 200

header_description = '''
Header rows serve as a structural component at the top of a dataset or table, defining the meaning and context of the columns below them.
They typically contain labels that describe the type of data in each column, acting as a guide for interpreting the table's contents.
In tables with hierarchical structures, header rows can span multiple levels, using features like colspans to group related columns visually. 
This layered organization allows for the representation of complex relationships between columns, improving clarity and facilitating detailed analysis of multidimensional data.
'''

label_description = '''
Label columns act as a structural component in a table, typically positioned on the left side, and provide descriptive or categorical identifiers for each row. 
They define the context or grouping of the data within the rows, allowing for easier reference and understanding of the dataset. 
In hierarchical tables, label columns can represent multiple levels of categorization, employing features like rowspans to visually group related rows under shared labels. 
This structure enables the organization of nested relationships within the data, enhancing readability and supporting more detailed analysis of grouped or hierarchical information.
'''

negative_description = '''
A column or row that is not classified as {mode_header_name} {mode} would typically be referred to as a data column or data row, respectively. 
These elements contain the core values or observations of the dataset.
Data columns: Positioned within the table body, they hold the actual measurements, metrics, or attributes corresponding to each row's label. They rely on header rows for context (e.g., the meaning of the values they contain).
Data rows: Found below the header row(s), they represent individual records, entries, or instances in the dataset. These rows are often linked to label columns for identification and provide the details of the data points.
'''

prompt_template = '''
You are tasked with analyzing table data to determine whether the provided {mode} should be classified as a {mode_header_name} or not.  

Instructions:
1. Review the provided {mode} and the next and previous {mode}s.
2. Consider typical properties of a {mode_header_name} {mode} when making your determination: For {mode_header_name} {mode}s typically yield: {mode_description}
3. End your response with one of the following:
   - "Answer: Yes" if the {mode} represents a {mode_header_name} {mode}.
   - "Answer: No" if the {mode} contains actual records or entries (e.g., numerical values, measurements, metrics or attributes corresponding to a category).
4. Reason your answer with maximum 150 tokens.

{mode} to Analyze:  
{line}

The {mode} index of the provided {mode} is {index}.

{previous_index}
{second_previous_index}

{next_index}
{second_next_index}

'''










