[run]
pipeline = true
indexing = false
analysis = false
evaluation = false

# choose from "sec-filings", "sec-filings-html-splitter"
mode = "sec-filings-html-splitter"

[qdrant]

# hostname (inside docker network) from Python/askecj perspective
# set to "localhost" if and only if you are working outside docker
# (if needed temporarily only, consider using --qdrant.hostname=localhost instead)
host = "localhost"
# host = "qdrant"

# Set the following value to the ports inside docker network (default: 6333, 6334).
# This setting may differ from the port bound on host set in .env!
port = 6333
grpc_port = 6334

# Name of the qdrant collection on which 
# indexing and retrieving will be based on.
index_name = "baseline-processed"

[ollama]

# hostname (inside docker network) from Python/askecj perspective
# set to "localhost" if and only if you are working outside docker
# (if needed temporarily only, consider using --ollama.host=localhost instead)
host = "localhost"
# host = "ollama"
port = 11434
temperature = 0

# choose out of "gemma:2b", "mistral-nemo"
model = "gemma:2b"

[huggingface]

# choose out of "mistralai/Mistral-Nemo-Instruct-2407", "google/gemma-2-2b-it"
generation_model = "mistralai/Mistral-Nemo-Instruct-2407"

# choose out of "sentence-transformers/all-MiniLM-l6-v2", "Snowflake/snowflake-arctic-embed-m-v1.5"
embedding_model = "Snowflake/snowflake-arctic-embed-m-v1.5"

[full_document_storage]
local_path = "./data/preprocessed_documents/"


[pipeline]
# choose out of ollama or huggingface
llm_implementation = "huggingface"

# choose out of HuggingFaceEmbeddings, NomicEmbeddings ...
embedding_tool = "HuggingFaceEmbeddings"

template = '''
You are tasked with answering questions based on specific financial documents. Your task is to give the correct answer based on the given context.
Respond with only the answer. Do not include words like "Answer" or "Response." Provide the answer as either:
- A number for questions about revenue, profit, or quantities.
- A word or phrase for questions about products, categories, or names.
- 'None' if the context doesn't provide information about the given question.

Do not include explanations, units, or any additional text. Provide only the final answer.

Example:
- What was the sales revenue of Company Y from 2022 to 2024?
  2,500
- What is the main product of Company Z?
  ZetaDrug
- What's stock market price of Company X in 2021?
  None

Context: \n {context}

Question: \n {question}
'''

[data]
path_local = "./data/sec_filings/"
path_local_evaluation = "./data/evaluation/SEC_Evaluation_Dataset.csv"

[nomic]
embedding_model = "nomic-embed-text-v1.5"
