[run]
pipeline = true
indexing = false
analysis = false
evaluation = false

# choose from "sec-filings", "wiki-tables"
dataset = "sec-filings"

[indexing]

# choose from "recursive-character", "recursive-character-html", "semantic"
chunking_strategy = "semantic"

# choose out of "huggingface", "nomic", "openai"...
embedding_method = "openai"

full_document_storage_path = "./data/preprocessed_documents/"


[text_generation]

# choose from "ollama", "huggingface-inference","openai", ...

method = "huggingface-inference"

prompt_template = '''
You are tasked with answering questions based on specific financial documents. Your task is to give the correct answer based on the given context.
Respond with only the answer. Do not include words like "Answer" or "Response." Provide the answer as either:
- A number for questions about revenue, profit, or quantities.
- A word or phrase for questions about products, categories, or names.
- 'None' if the context doesn't provide information about the given question.

Do not include explanations, units, or any additional text. Provide only the final answer.

Example:
- What was the sales revenue of Company Y from 2022 to 2024?
  2,500
- What is the main product of Company Z?
  ZetaDrug
- What's stock market price of Company X in 2021?
  None

Context: 
{context}

Question: {question}
'''

[ollama]

# choose out of "gemma:2b", "mistral-nemo"
model = "gemma:2b"

[huggingface]

# choose out of "mistralai/Mistral-Nemo-Instruct-2407", "google/gemma-2-2b-it"
generation_model = "mistralai/Mistral-Nemo-Instruct-2407"

# choose out of "sentence-transformers/all-MiniLM-l6-v2", "Snowflake/snowflake-arctic-embed-m-v1.5", "Alibaba-NLP/gte-base-en-v1.5"
embedding_model = "sentence-transformers/all-MiniLM-l6-v2"

[nomic]
embedding_model = "nomic-embed-text-v1.5"

[openai]
embedding_model = "text-embedding-ada-002"

[sec_filings]
data_path = "./data/sec_filings/"
data_path_single = "./data/sec_filings/awk-20231231.htm"
evaluation_data_path = "./data/evaluation/SEC_Evaluation_Dataset_AWW.csv"

# Options are 
#       - "none", 
#       - "remove-attributes", 
#       - "remove-xbrl", 
#       - "remove-invisible", 
#       - "remove-spans-a", 
#       - "split-into-reduced-sections", 
#       - "split-into-table-and-text", 
#       - "only-text-except-tables". 

# As soon as "none" is in the list, there will be no preprocessing
preprocess_mode = ["only-text-except-tables", "remove-attributes", "remove-xbrl", "remove-invisible", "remove-spans-a"]
preprocess_mode_index_name = "only-text-except-tables"
[wiki_tables]



